// apps/react/src/App.tsx
import { useState } from 'react';
import McTestDemo from './components/McTestDemo'
// hygen:new:component_demo:import:react


function App() {
  
  const [templates] = useState([
    {
      name: 'McTest',
      component: () => (<McTestDemo />)
    },
    // hygen:new:component_demo:template:react
  ])

  

  return (
    <>
      <div>
        <h1>React: Component Listing</h1>
        {templates.map((template, index) => (
          <div key={index}>
            <h2>{template.name}</h2>
            <template.component />
            <hr />
          </div>
        ))}
      </div>
    </>
  )
}

export default App

// apps/vue/src/App.vue
<script setup lang="ts">
  import { ref } from 'vue'

  const templates = ref([
    {
      name: 'McTest',
      component: 'mc-test-demo'
    },
    // hygen:new:component_demo:template:vue
  ])
</script>

<template>
  <div>
    <h1>Vue: Component Listing</h1>
    <template v-for="(template, index) in templates" :key="index">
      <div>
        <h2>{{ template.name }}</h2>
        <component :is="template.component" />
        <hr />
      </div>
    </template>
  </div>
</template>

<style scoped>

</style>
