// apps/vue/src/components/McTestDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { McTest } from '@placid/vue'

const McTestRef = ref(null);
const McTestValidationMessage = ref('') 

</script>

<template>
  <div>
    <McTest
      ref="McTestRef"
      name='test' 
      />
  </div>
  <div>Validation Message: {{ McTestValidationMessage }}</div>
  <div>
    <button @click="() => { 
      console.log(McTestRef.value?.validate)
        if (McTestRef.value && typeof McTestRef.value.validate === 'function') {
          McTestRef.value?.validate()
            .then((validation: unknown) => {
              console.log(validation)
              McTestValidationMessage.value = JSON.stringify(validation) || ''
            })
            .catch((error) => console.error('Validation Error:', error))
          }
        }">
      Validate
    </button>
  </div>
</template>

// apps/react/src/components/McTestDemo.tsx
import { useRef, useState } from 'react';
import { McTest } from '@placid/react'

type UIComponentType = {
  validate: () => Promise<unknown>
} 

function McTestDemo() {
  const McTestRef = useRef<UIComponentType>();
  const [McTestValidationMessage, setMcTestValidationMessage] = useState('') 

  return (
    <>
      <div><McTest name='test' ref={ McTestRef } /></div>
      <div>Validation Message: { McTestValidationMessage } </div>
      <div>
        <button onClick={() => { 
            McTestRef.current?.validate()
              .then((validation: unknown) => {
                setMcTestValidationMessage(JSON.stringify(validation) || '')
              })
              .catch((error) => console.error('Validation Error:', error))
            }}>
          Validate
        </button>
      </div>
    </>
  )
}

export default McTestDemo
